### ISSUE TITLE
Explanation of version numbers in README.md

### ISSUE THREAD

**Issue by marhkb** [JetBrains/jdk8u#12]
They seem totally mixed. 
Version 1024.12 is newer than 1036.7 though the version number is less.
Which one should I use?
I could find no explanation.
Please add an explanation to README.md.

**Comment by IceMan81** [comment]
I know it's quite confusing. Yesterday 1136.7 was released and just now I got a bintray alert saying 1136.6 was released. 
I think some of them are builds for different branches for different Intellij releases but having some explanation of this would be very helpful.

**Comment by avu** [comment]
The main idea is to have a sequence of the builds in the master branch and then create stable branches from successful master builds for releasing IJ products. Dot numbers mean critical updates to the stable build
