### ISSUE TITLE
Does not build on Linux Kernel 5

### ISSUE THREAD

**Issue by kaismh** [JetBrains/jdk8u#16]
Could not build it on Arch Linux 5.0.2-arch1-1-ARCH, 

The error message is This OS is not supported: Linux  5.0.2-arch1-1-ARCH

**Comment by artizirk** [comment]
Setting `DISABLE_HOTSPOT_OS_VERSION_CHECK=ok` env variable should do the trick

source: https://stackoverflow.com/questions/14285820/os-not-supported-error-while-building-hotspot

**Comment by kaismh** [comment]
@artizirk  Many Thanks, worked great
