### ISSUE TITLE
Is there a way to programmatically detect the JetBrains JRE?

### ISSUE THREAD

**Issue by mikehearn** [JetBrains/jdk8u#5]
I'd like to enable use of emoji in the UI only when the underlying JRE supports it, but I'm not sure how to detect if I'm running on your JRE or not.

**Comment by mikehearn** [comment]
Never mind, now I feel stupid. Of course, the bulk of the patches are in the sub-repositories. I interpreted the README to mean the other repos weren't used (just there for the build) but of course that's where the patches are. Rummaging through the code shows that the java.vendor system property is overridden.

**Comment by bulenkov** [comment]
Hello Mike. If you're writing an IntelliJ IDEA plugin, please use SystemInfo.isJetbrainsJvm
Otherwise,
```
private static boolean isJetbrainsJvm() {
  final String vendor = SystemProperties.getJavaVendor();
  return vendor != null && StringUtil.containsIgnoreCase(vendor, "JetBrains");
}
```
